#!/data/data/com.termux/files/usr/bin/python3

from os import system,remove
from sys import argv
import re,argparse

class BashObf(object):
	def __init__(self,file,out):
		self.file = file
		self.out = out
		self.main()
	def main(self):
		try:
			_i = re.sub(r'eval','echo',open(self.file).read())
			with open('tmp.sh','w') as f:
				f.write(_i)
				f.close()
			system(f'sh tmp.sh > {self.out}')
			remove('tmp.sh')
			system('clear')
			print(f'[*] File saved as: {self.out}')
			_ = input('[*] Ver impresion? (y/n) : ')
			if _.lower() == 'y':
				system(f'cat {self.out}')
			else:
				exit()
		except Exception as eror:
			exit(f'[*] ¡Opps!  Algo salió mal: {str(eror)}')

try:
	system('clear')
	arg = argparse.ArgumentParser(description='Scripts de-obfuscation ',formatter_class=argparse.RawTextHelpFormatter)
	arg.add_argument('-i','--infile',help='\033[1;33mfile for deobfuscation\033[0m',metavar='')
	arg.add_argument('-o','--output',help='\033[1;32mSave output file\033[0m',metavar='')
	gc_ = arg.add_argument_group('Adicional')
	gc_.add_argument('-c','--contact',help='Contact information',action='store_true')
	gc_.add_argument('-v','--version',help='Version script',action='store_true')
	oo_ = arg.parse_args()
	if oo_.infile and oo_.output:
		BashObf(oo_.infile,oo_.output)
	elif oo_.contact:
		system('xdg-open https://github.com/barba99')
	elif oo_.version:
		print('1.0 Copyright © 2020 BY JORGE BARBA')
	else:
		print(f"\033[0;37m Developed by:\033[0;36m @JorgeBarba\033[0m""")
		exit(f"""\033[1;32m decode -h \033[1;33mto show all options\033[0m""")
except EOFError:
	pass
